auto: true
markdown: rdiscount
pygments: true

title: we are talking on the web

url: http://9034725985.github.com/web/

permalink: /:year/:month/:day/:title/

author:
    name: Kushal 
    email: kushaldeveloper@gmail.com
    github: 9034725985
    twitter: 9034725985
    gravatar: http://www.gravatar.com/avatar/5b7d3122776b44cfb18ed7aa865804a1.png

comments:
    provider: disqus
    disqus:
        short_name: intheatticuk
        
analytics:
    provider: google 
    google: 
        tracking_id: 'UA-18015420-1'
        domain: 'in-the-attic.com'
